name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать на push в основную ветку

jobs:
  test:
    runs-on: ubuntu-latest  # Для тестов можно использовать Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest calculator/TestCalculator.py

  deploy:
    runs-on: ubuntu-latest  # Для деплоя используем Ubuntu
    needs: test  # Этот шаг выполняется только после успешного тестирования
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Linux
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} denis@192.168.0.211 << 'EOF'
            cd /home/Projects/calculator/
            git pull origin main
            cd calculator
            python main.py
          EOF
